package smops.hibernate;
// Generated Jun 17, 2014 10:27:47 AM by Hibernate Tools 3.6.0



/**
 * Field generated by hbm2java
 */
public class Field  implements java.io.Serializable {


     private Integer id;
     private Form form;
     private String name;
     private String type;
     private String value;
     private String label;
     private String html;
     private String infoType;

    public Field() {
    }

    public Field(Form form, String name, String type, String value, String label, String html, String infoType) {
       this.form = form;
       this.name = name;
       this.type = type;
       this.value = value;
       this.label = label;
       this.html = html;
       this.infoType = infoType;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Form getForm() {
        return this.form;
    }
    
    public void setForm(Form form) {
        this.form = form;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    public String getHtml() {
        return this.html;
    }
    
    public void setHtml(String html) {
        this.html = html;
    }
    public String getInfoType() {
        return this.infoType;
    }
    
    public void setInfoType(String infoType) {
        this.infoType = infoType;
    }




}


