package smops.hibernate;
// Generated Jun 17, 2014 10:27:47 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Form generated by hbm2java
 */
public class Form  implements java.io.Serializable {


     private Integer id;
     private Business business;
     private String action;
     private String pageUrl;
     private String title;
     private String html;
     private String purpose;
     private String fileName;
     private Set fields = new HashSet(0);

    public Form() {
    }

    public Form(Business business, String action, String pageUrl, String title, String html, String purpose, String fileName, Set fields) {
       this.business = business;
       this.action = action;
       this.pageUrl = pageUrl;
       this.title = title;
       this.html = html;
       this.purpose = purpose;
       this.fileName = fileName;
       this.fields = fields;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Business getBusiness() {
        return this.business;
    }
    
    public void setBusiness(Business business) {
        this.business = business;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }
    public String getPageUrl() {
        return this.pageUrl;
    }
    
    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getHtml() {
        return this.html;
    }
    
    public void setHtml(String html) {
        this.html = html;
    }
    public String getPurpose() {
        return this.purpose;
    }
    
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public Set getFields() {
        return this.fields;
    }
    
    public void setFields(Set fields) {
        this.fields = fields;
    }




}


