package smops.hibernate;
// Generated Jul 15, 2014 3:02:40 PM by Hibernate Tools 3.6.0



/**
 * JsBusiness generated by hbm2java
 */
public class JsBusiness  implements java.io.Serializable {


     private Integer id;
     private Business business;
     private JsLib jsLib;
     private String url;

    public JsBusiness() {
    }

    public JsBusiness(Business business, JsLib jsLib, String url) {
       this.business = business;
       this.jsLib = jsLib;
       this.url = url;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Business getBusiness() {
        return this.business;
    }
    
    public void setBusiness(Business business) {
        this.business = business;
    }
    public JsLib getJsLib() {
        return this.jsLib;
    }
    
    public void setJsLib(JsLib jsLib) {
        this.jsLib = jsLib;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


