package smops.hibernate;
// Generated Jul 15, 2014 3:02:40 PM by Hibernate Tools 3.6.0



/**
 * SealBusiness generated by hbm2java
 */
public class SealBusiness  implements java.io.Serializable {


     private Integer id;
     private Business business;
     private String seal;
     private String sealUrl;
     private String sealAnchorText;

    public SealBusiness() {
    }

    public SealBusiness(Business business, String seal, String sealUrl, String sealAnchorText) {
       this.business = business;
       this.seal = seal;
       this.sealUrl = sealUrl;
       this.sealAnchorText = sealAnchorText;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Business getBusiness() {
        return this.business;
    }
    
    public void setBusiness(Business business) {
        this.business = business;
    }
    public String getSeal() {
        return this.seal;
    }
    
    public void setSeal(String seal) {
        this.seal = seal;
    }
    public String getSealUrl() {
        return this.sealUrl;
    }
    
    public void setSealUrl(String sealUrl) {
        this.sealUrl = sealUrl;
    }
    public String getSealAnchorText() {
        return this.sealAnchorText;
    }
    
    public void setSealAnchorText(String sealAnchorText) {
        this.sealAnchorText = sealAnchorText;
    }




}


