package smops.hibernate;
// Generated Jun 10, 2014 4:22:28 PM by Hibernate Tools 3.6.0



/**
 * Tracker generated by hbm2java
 */
public class Tracker  implements java.io.Serializable {


     private Integer id;
     private Business business;
     private Integer type;
     private String url;

    public Tracker() {
    }

    public Tracker(Business business, Integer type, String url) {
       this.business = business;
       this.type = type;
       this.url = url;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Business getBusiness() {
        return this.business;
    }
    
    public void setBusiness(Business business) {
        this.business = business;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


