package smops.hibernate;
// Generated Jul 15, 2014 3:02:40 PM by Hibernate Tools 3.6.0



/**
 * TrackerBusiness generated by hbm2java
 */
public class TrackerBusiness  implements java.io.Serializable {


     private Integer id;
     private Business business;
     private String trackerUrl;
     private String type;
     private String fullUrl;

    public TrackerBusiness() {
    }

    public TrackerBusiness(Business business, String trackerUrl, String type, String fullUrl) {
       this.business = business;
       this.trackerUrl = trackerUrl;
       this.type = type;
       this.fullUrl = fullUrl;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Business getBusiness() {
        return this.business;
    }
    
    public void setBusiness(Business business) {
        this.business = business;
    }
    public String getTrackerUrl() {
        return this.trackerUrl;
    }
    
    public void setTrackerUrl(String trackerUrl) {
        this.trackerUrl = trackerUrl;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getFullUrl() {
        return this.fullUrl;
    }
    
    public void setFullUrl(String fullUrl) {
        this.fullUrl = fullUrl;
    }




}


