package smops.hibernate;
// Generated Jun 19, 2014 11:11:54 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tracker generated by hbm2java
 */
public class Tracker  implements java.io.Serializable {


     private int id;
     private String name;
     private String description;
     private String type;
     private Set trackerBusinesses = new HashSet(0);

    public Tracker() {
    }

	
    public Tracker(int id) {
        this.id = id;
    }
    public Tracker(int id, String name, String description, String type, Set trackerBusinesses) {
       this.id = id;
       this.name = name;
       this.description = description;
       this.type = type;
       this.trackerBusinesses = trackerBusinesses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getTrackerBusinesses() {
        return this.trackerBusinesses;
    }
    
    public void setTrackerBusinesses(Set trackerBusinesses) {
        this.trackerBusinesses = trackerBusinesses;
    }




}


